Branch for merge request test feature
SURFscz/plsc pull request #8
Opened 2021-02-02 12:42 UTC by HarryKodden

Have prepared merge request for merging the test feature with latest version of main

2021-02-02 13:25 UTC, baszoetekouw requested changes
Zie de inline comments.  Is het echt nodig de files te renamen?  Ik kan nu namelijk niet makkelijk checken wat er binnen de file is veranderd.

2021-02-02 13:25 UTC, baszoetekouw commented on run.sh
> +/usr/bin/env python plsc_flat.py "$1"
dit maakt prod kapot, omdat daar python in een venv staat (in de huidige dir).

2021-02-02 13:25 UTC, baszoetekouw commented on plsc
> -#!/usr/bin/env python3
Waarom hernoem je deze files allemaal naar .py?  Ik kan nu namelijk niet zoen wat er is veranderd na de rename.

2021-02-02 13:25 UTC, baszoetekouw commented on requirements.txt
> +json-server.py
Graag aparte requirements maken voor test (kijk naar SBS hoe Okke dat daar heeft opgelost)

2021-02-02 13:25 UTC, baszoetekouw commented on sbs.py
> +        co = self.collaboration(c_id)
Wat is dit voor change?

2021-02-02 13:25 UTC, baszoetekouw commented on sbs.py
> +        co = self.collaboration(c_id)
Wat doet dit?

2021-02-02 13:25 UTC, baszoetekouw commented on plsc_ordered.py
> +#!/usr/bin/env python3
Wat is hier veranderd?  Kan het niet zien door de rename...

2021-02-02 13:35 UTC, HarryKodden commented
Reden dat ik hernoem is omdat ik die files als module wil kunnen gebruiken. (Files die je in python wilt importeren moeten eindigen op .py en mogen geen ‘-‘ bevatten)

Zie ’tests/base_test.py’

import plsc_ordered
import plsc_flat

> On 2 Feb 2021, at 14:25, Bas Zoetekouw <notifications@github.com> wrote:
> 
> 
> @baszoetekouw requested changes on this pull request.
> 
> Zie de inline comments. Is het echt nodig de files te renamen? Ik kan nu namelijk niet makkelijk checken wat er binnen de file is veranderd.
> 
> In run.sh <https://github.com/SURFscz/plsc/pull/8#discussion_r568593691>:
> 
> > @@ -11,6 +12,5 @@ elif [ ! -f "$1" ]; then
>    exit 1
>  fi
> 
> -#bin/python ./plsc "$1"
> -bin/python ./slp-ordered "$1"
> -bin/python ./plsc-flat "$1"
> +/usr/bin/env python plsc_ordered.py "$1"
> +/usr/bin/env python plsc_flat.py "$1"
> dit maakt prod kapot, omdat daar python in een venv staat (in de huidige dir).
> 
> In plsc <https://github.com/SURFscz/plsc/pull/8#discussion_r568594648>:
> 
> > @@ -1,256 +0,0 @@
> -#!/usr/bin/env python3
> Waarom hernoem je deze files allemaal naar .py? Ik kan nu namelijk niet zoen wat er is veranderd na de rename.
> 
> In requirements.txt <https://github.com/SURFscz/plsc/pull/8#discussion_r568595549>:
> 
> > @@ -8,3 +8,6 @@ PyYAML
>  future-fstrings
>  ipdb
>  requests
> +pytest
> +pytest-dotenv
> +json-server.py
> Graag aparte requirements maken voor test (kijk naar SBS hoe Okke dat daar heeft opgelost)
> 
> In sbs.py <https://github.com/SURFscz/plsc/pull/8#discussion_r568596319>:
> 
> >          users = {}
> -        groups = self.groups(co)
> -        #co = self.collaboration(c_id)
> +        co = self.collaboration(c_id)
> Wat is dit voor change?
> 
> In sbs.py <https://github.com/SURFscz/plsc/pull/8#discussion_r568596519>:
> 
> >          groups = {}
> -        #co = self.collaboration(c_id)
> +        co = self.collaboration(c_id)
> Wat doet dit?
> 
> In plsc_ordered.py <https://github.com/SURFscz/plsc/pull/8#discussion_r568597394>:
> 
> > @@ -0,0 +1,444 @@
> +#!/usr/bin/env python3
> Wat is hier veranderd? Kan het niet zien door de rename...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/SURFscz/plsc/pull/8#pullrequestreview-581331269>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAOB5SPLJTDM37ST53T2JRTS474OLANCNFSM4W6SE4KQ>.
>

2021-02-02 13:36 UTC, baszoetekouw commented
ok, dan maak ik even met de hand een diff.  Die changs in sbs.py lijken wel ongerelateerd?

2021-03-02 11:07 UTC, baszoetekouw commented
Met de hand gemerged

2021-03-02 11:07 UTC, closed without merging